### ISSUE TITLE
Why IDENT is OFF ?

### ISSUE THREAD

**Issue by fahadmehar** [StormBit/stormbit.github.io#18]
Hello, Why my BNC IDENT Is OFF ? ~Deadite@ ???  I use server DALnet there rules are bit strick...

**Comment by mikotohe2** [comment]
This is the repository for the StormBit website; not the BNC. Please ask in #stormbnc on irc.stormbit.net for BNC queries. Issue closed.

**Comment by antoligy** [comment]
Please use https://github.com/StormBit/stormbnc for issues with StormBNC.

@mikotohe2 Worth documenting this for future people?

**Comment by mikotohe2** [comment]
Yeah, it might be worth it - but I feel like github issues should still be reserved for actual technical issues; what we need to focus on is making sure people can get user support in IRC for user-stuff.

**Comment by fahadmehar** [comment]
Thanks antoligy for help

**Comment by fahadmehar** [comment]
mikotoh2: All Issues should be discuss

**Comment by fahadmehar** [comment]
@mikotohe2  I wait for hours in that channel none response.

**Comment by antoligy** [comment]
To me this was a technical issue, as it was a genuine question about
something we don't seem to support.
